### ISSUE TITLE
gr_ray_tracing_model.py 中 32 行公式似乎不对

### ISSUE THREAD

**Issue by zhaozhh** [theAfish/BlackHoleRayMarching#2]
原公式

`            dudphi += - u * (1 - 3 / 2 * u ** 2) * dphi`

应该为：

`            dudphi += - u * (1 - 3 / 2 * u ) * dphi`

**Comment by theAfish** [comment]
牛！感谢更正！经检查确实为本人公式输入错误，已经更新代码。
