### ISSUE TITLE
能够透露一下，颜色取值的背后原则吗

### ISSUE THREAD

**Issue by zhaozhh** [theAfish/BlackHoleRayMarching#3]
问题就是，为何下面的代码要写成这样？

```

color += ti.Vector([1/(exp((r-4.9)/0.03)+1), 
                                        2/(exp((r-5)/0.3)+1)-1, -(r+3)**3*(r-5)/432])
```

**Comment by theAfish** [comment]
这里当时是为了给吸积盘提供一个RGB颜色而手动调节获得的。主要考虑的是色彩美观，没有什么真实物理意义。如果要真实考虑多普勒效应与引力红移等，此处应该换成更加符合物理的函数形式。

**Comment by zhaozhh** [comment]
我在gr_ray_tracing_model.py 的类Ray中定义了一个波长变RGB的子程序，为何调用的时候会出错呢？

子程序如下：

 ```
@ti.func
    def wavelength_to_rgb(wavelength, gamma=0.8): 
        wavelength = float(wavelength)
        if wavelength >= 380 and wavelength <= 440:
            attenuation = 0.3 + 0.7 * (wavelength - 380) / (440 - 380)
            R = ((-(wavelength - 440) / (440 - 380)) * attenuation) ** gamma
            G = 0.0
            B = (1.0 * attenuation) ** gamma
        elif wavelength >= 440 and wavelength <= 490:
            R = 0.0
            G = ((wavelength - 440) / (490 - 440)) ** gamma
            B = 1.0
        elif wavelength >= 490 and wavelength <= 510:
            R = 0.0
            G = 1.0
            B = (-(wavelength - 510) / (510 - 490)) ** gamma
        elif wavelength >= 510 and wavelength <= 580:
            R = ((wavelength - 510) / (580 - 510)) ** gamma
            G = 1.0
            B = 0.0
        elif wavelength >= 580 and wavelength <= 645:
            R = 1.0
            G = (-(wavelength - 645) / (645 - 580)) ** gamma
            B = 0.0
        elif wavelength >= 645 and wavelength <= 750:
            attenuation = 0.3 + 0.7 * (750 - wavelength) / (750 - 645)
            R = (1.0 * attenuation) ** gamma
            G = 0.0
            B = 0.0
        else:
            R = 0.0
            G = 0.0
            B = 0.0
        R *= 255
        G *= 255
        B *= 255
        return [int(R), int(G), int(B)]
```

调用：


```
@ti.func
    def update_euler(self):
        print(self.wavelength_to_rgb(600))
........
```

错误如下：


PS D:\yun\WorkSpace\RelativityObjects\BlackHoleRayMarching-master\BlackHoleRayMarching-master> & "D:/Program Files/Python311/python.exe" d:/yun/WorkSpace/RelativityObjects/BlackHoleRayMarching-master/BlackHoleRayMarching-master/main.py
[Taichi] version 1.7.2, llvm 15.0.1, commit 0131dce9, win, python 3.11.4
[Taichi] Starting on arch=cuda
d:\yun\WorkSpace\RelativityObjects\BlackHoleRayMarching-master\BlackHoleRayMarching-master\gr_ray_tracing_model.py:205: SyntaxWarning: Calling non-taichi function "Ray". Scope inside the function is not processed by the Taichi AST transformer. The function may not work as expected. Proceed with caution! Maybe you can consider turning it into a @ti.func?
  return Ray(self.cam_origin[None],
Traceback (most recent call last):
  File "d:\yun\WorkSpace\RelativityObjects\BlackHoleRayMarching-master\BlackHoleRayMarching-master\main.py", line 68, in <module>
    render()
  File "C:\Users\zhaozhh\AppData\Roaming\Python\Python311\site-packages\taichi\lang\kernel_impl.py", line 1117, in wrapped
    raise type(e)("\n" + str(e)) from None
taichi.lang.exception.TaichiCompilationError:
File "d:\yun\WorkSpace\RelativityObjects\BlackHoleRayMarching-master\BlackHoleRayMarching-master\main.py", line 42, in render:
            color += ray.update_euler()
                     ^^^^^^^^^^^^^^^^^^
File "d:\yun\WorkSpace\RelativityObjects\BlackHoleRayMarching-master\BlackHoleRayMarching-master\gr_ray_tracing_model.py", line 65, in update_euler:      
        print(self.wavelength_to_rgb(600))
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "d:\yun\WorkSpace\RelativityObjects\BlackHoleRayMarching-master\BlackHoleRayMarching-master\gr_ray_tracing_model.py", line 25, in wavelength_to_rgb: 
        wavelength = float(wavelength)
                     ^^^^^^^^^^^^^^^^^
Traceback (most recent call last):
  File "C:\Users\zhaozhh\AppData\Roaming\Python\Python311\site-packages\taichi\lang\ast\ast_transformer_utils.py", line 27, in __call__
    return method(ctx, node)
           ^^^^^^^^^^^^^^^^^
  File "C:\Users\zhaozhh\AppData\Roaming\Python\Python311\site-packages\taichi\lang\ast\ast_transformer.py", line 587, in build_Call
    if ASTTransformer.build_call_if_is_builtin(ctx, node, args, keywords):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\zhaozhh\AppData\Roaming\Python\Python311\site-packages\taichi\lang\ast\ast_transformer.py", line 443, in build_call_if_is_builtin        
    node.ptr = replace_func[id(func)](*args, **keywords)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\zhaozhh\AppData\Roaming\Python\Python311\site-packages\taichi\lang\util.py", line 342, in wrapped
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\zhaozhh\AppData\Roaming\Python\Python311\site-packages\taichi\lang\impl.py", line 991, in ti_float
    return float(_var)
           ^^^^^^^^^^^
TypeError: float() argument must be a string or a real number, not 'Ray'

**Comment by zhaozhh** [comment]
wavelength_to_rgb() 是类Ray中的函数。


`TypeError: float() argument must be a string or a real number, not 'Ray'`

只是简单的调用函数，怎么转到类Ray上呢？好奇怪

**Comment by theAfish** [comment]
由于是类方法，在定义taichi函数时要加self，同时我记得taichi需要在使用函数前需要提前声明变量，否则会报错（需要先声明R = 0.0... 这样）。修改为如下代码结果是否正确？

```
    @ti.func
    def wavelength_to_rgb(self, wavelength, gamma=0.8):
        wavelength = ti.float32(wavelength)
        R = 0.0
        G = 0.0
        B = 0.0
        if wavelength >= 380 and wavelength <= 440:
            attenuation = 0.3 + 0.7 * (wavelength - 380) / (440 - 380)
            R = ((-(wavelength - 440) / (440 - 380)) * attenuation) ** gamma
            G = 0.0
            B = (1.0 * attenuation) ** gamma
        elif wavelength >= 440 and wavelength <= 490:
            R = 0.0
            G = ((wavelength - 440) / (490 - 440)) ** gamma
            B = 1.0
        elif wavelength >= 490 and wavelength <= 510:
            R = 0.0
            G = 1.0
            B = (-(wavelength - 510) / (510 - 490)) ** gamma
        elif wavelength >= 510 and wavelength <= 580:
            R = ((wavelength - 510) / (580 - 510)) ** gamma
            G = 1.0
            B = 0.0
        elif wavelength >= 580 and wavelength <= 645:
            R = 1.0
            G = (-(wavelength - 645) / (645 - 580)) ** gamma
            B = 0.0
        elif wavelength >= 645 and wavelength <= 750:
            attenuation = 0.3 + 0.7 * (750 - wavelength) / (750 - 645)
            R = (1.0 * attenuation) ** gamma
            G = 0.0
            B = 0.0
        R *= 255
        G *= 255
        B *= 255
        return [int(R), int(G), int(B)]
```

**Comment by zhaozhh** [comment]
非常感谢，程序不报错了！！！

**Comment by zhaozhh** [comment]
非常感谢，程序不报错了！！！

**Comment by zhaozhh** [comment]
非常感谢，程序不报错了！！！
